services:
  auth:
    volumes:
      - ./containers/services/auth/app:/app/
    command: watchmedo auto-restart --recursive --patterns="*.py" -- python -m main
  api:
    volumes:
      - ./containers/services/api/app:/app/app
    command: watchmedo auto-restart --recursive --patterns="*.py" -- python -m app.main

  game:
    volumes:
      - ./containers/services/game/app:/app/app
    command: watchmedo auto-restart --recursive --patterns="*.py" -- python -m app.main

  website:
    volumes:
      - ./containers/services/website/app:/app/app
    command: watchmedo auto-restart --recursive --patterns="*.py" -- python -m app.main
