services:
  nginx:
    container_name: service_nginx
    build: ./containers/services/nginx
    restart: on-failure
    env_file:
      - .env
    volumes:
      - nginx_data:/var/www/nginx
    depends_on:
      - website
    networks:
      - website_network
  website:
    container_name: service_website
    build: ./containers/services/website
    restart: on-failure
    env_file:
      - .env
    volumes:
      - website_data:/var/www/website
    depends_on:
      - api
    networks:
      - website_network
      - api_network
  api:
    container_name: service_api
    build: ./containers/services/api
    restart: on-failure
    env_file:
      - .env
    volumes:
      - api_data:/var/www/api
    networks:
      - api_network
      - website_network
      - auth_network
      - game_network
      - user_db_network
  auth:
    container_name: service_auth
    build: ./containers/services/auth
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - auth_db
    networks:
      - auth_network
      - auth_db_network
  game:
    container_name: service_game
    build: ./containers/services/game
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - game_db
    networks:
      - game_network
      - game_db_network
  auth_db:
    container_name: auth_db
    build: ./containers/databases/auth_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - auth_db_data:/var/lib/mysql
    networks:
      - auth_db_network
  game_db:
    container_name: game_db
    build: ./containers/databases/game_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - game_db_data:/var/lib/mysql
    networks:
      - game_db_network
  user_db:
    container_name: user_db
    build: ./containers/databases/user_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - user_db_data:/var/lib/mysql
    networks:
      - user_db_network

volumes:
  nginx_data:
  website_data:
  api_data:
  auth_db_data:
  game_db_data:
  user_db_data:

networks:
  mariadb_network:
    driver: bridge
  api_network:
    driver: bridge
  auth_network:
    driver: bridge
  game_network:
    driver: bridge
  website_network:
    driver: bridge
  auth_db_network:
    driver: bridge
  game_db_network:
    driver: bridge
  user_db_network:
    driver: bridge
